# Generated by Django 4.1.7 on 2023-03-03 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_area', models.FloatField()),
                ('legal_reserve_area', models.FloatField()),
                ('has_matricula_certificate', models.BooleanField()),
                ('pdf_matricula_certificate', models.FileField(upload_to='matricula_certificate/')),
                ('address', models.CharField(max_length=255)),
                ('documentation_up_to_date', models.BooleanField()),
                ('has_car', models.BooleanField()),
                ('status_car', models.CharField(choices=[('Ativo', 'Ativo'), ('Pendente', 'Pendente'), ('Cancelado', 'Cancelado'), ('', 'Não possui')], default='', max_length=10)),
                ('sicar_code', models.CharField(max_length=20)),
                ('pdf_car', models.FileField(upload_to='car/')),
                ('matricula_status', models.CharField(max_length=20)),
                ('georeferencing_status', models.CharField(max_length=20)),
                ('has_georeferencing_file', models.BooleanField()),
                ('property_polygon', models.FileField(upload_to='property_polygon/')),
                ('reserve_legal_status', models.CharField(max_length=50)),
                ('has_reserve_legal_deficit', models.BooleanField()),
                ('physical_or_legal_entity', models.CharField(max_length=20)),
                ('cnpj', models.IntegerField(null=True)),
                ('conservation_unit', models.CharField(max_length=50)),
                ('federal_debt', models.BooleanField()),
                ('pdf_federal_debt_certificate', models.FileField(upload_to='federal_debt/')),
                ('has_updated_ccir', models.BooleanField()),
                ('pdf_ccir', models.FileField(upload_to='ccir/')),
                ('owner_actions_to_preserve_forest', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
