# Generated by Django 4.1.7 on 2023-05-02 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="default", max_length=100)),
                ("total_area", models.FloatField(blank=True)),
                ("legal_reserve_area", models.FloatField(blank=True)),
                ("address", models.CharField(blank=True, max_length=200)),
                ("status_car", models.CharField(blank=True, max_length=200)),
                ("sicar_code", models.CharField(blank=True, max_length=200)),
                ("matricula_status", models.CharField(blank=True, max_length=200)),
                ("georeferencing_status", models.CharField(blank=True, max_length=200)),
                ("reserve_legal_status", models.CharField(blank=True, max_length=200)),
                (
                    "physical_or_legal_entity",
                    models.CharField(blank=True, max_length=200),
                ),
                ("cnpj", models.CharField(blank=True, max_length=200, null=True)),
                ("conservation_unit", models.CharField(blank=True, max_length=200)),
                ("owner_actions_to_preserve_forest", models.TextField(blank=True)),
                ("legal_reserve_deficit", models.BooleanField(blank=True, null=True)),
                ("has_federal_debt", models.BooleanField(blank=True, null=True)),
                (
                    "pdf_matricula_certificate",
                    models.FileField(
                        blank=True, null=True, upload_to="matricula_certificate/"
                    ),
                ),
                ("pdf_car", models.FileField(blank=True, null=True, upload_to="car/")),
                (
                    "property_polygon",
                    models.FileField(
                        blank=True, null=True, upload_to="property_polygon/"
                    ),
                ),
                (
                    "pdf_federal_debt_certificate",
                    models.FileField(blank=True, null=True, upload_to="federal_debt/"),
                ),
                (
                    "pdf_ccir",
                    models.FileField(blank=True, null=True, upload_to="ccir/"),
                ),
                ("score", models.IntegerField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=60, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
