# Generated by Django 4.1.7 on 2023-03-22 04:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="has_federal_debt",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="legal_reserve_deficit",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
