# Generated by Django 4.1.7 on 2023-04-28 20:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = []
