# Generated by Django 4.1.7 on 2023-05-12 22:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="password",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
