# Generated by Django 4.1.7 on 2023-05-03 13:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_auto_20230428_2046"),
    ]

    operations = []
