# Generated by Django 4.1.7 on 2023-03-28 01:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_alter_project_has_federal_debt_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="address",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="project",
            name="cnpj",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="conservation_unit",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="project",
            name="georeferencing_status",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="project",
            name="matricula_status",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="project",
            name="physical_or_legal_entity",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="project",
            name="reserve_legal_status",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="project",
            name="sicar_code",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="project",
            name="status_car",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
